from __future__ import annotations

from bot.db.schema import init_db
from bot.db.repository import (
    add_favorite,
    add_history_entry,
    count_categories,
    count_favorites,
    count_history,
    count_items_by_category,
    count_search_items,
    count_search_items_by_category,
    create_category,
    create_file_item,
    create_link_item,
    delete_category,
    delete_item,
    format_categories_list,
    get_category,
    get_category_by_name,
    get_item,
    get_item_by_video_id,
    get_item_by_url,
    is_favorite,
    list_categories,
    list_categories_with_counts,
    list_categories_with_counts_paged,
    list_favorites,
    list_history,
    list_items_by_category,
    list_items_by_marca_subcategoria,
    list_marcas,
    list_subcategorias_by_marca,
    remove_favorite,
    search_items,
    search_items_by_category,
    update_item_telegram_message_id,
)
